---
- name: Test ansible is installed
  shell: ansible --version
  register: ansible_is_installed

- name: Run install script as sudo
  script: setup.sh
  sudo: yes
  when: "ansible_is_installed|failed and ansible_distribution == 'Ubuntu'"
  register: ansible_init_used_sudo

- name: Run install script without sudo
  script: setup.sh
  when: ansible_is_installed|failed and ansible_init_used_sudo|skipped
